[package]
name = "shared"
version = "0.1.0"
authors = ["Erik Escher <erik@erikescher.de>"]
edition = "2018"

[dependencies]
sequoia-openpgp = "1"
anyhow = "1"
tokio = { version = "0.2", features = ["full"] } # outdated version in use with sequoia-net